import { DiagramStyles } from '@swirly/types'

export const baseStyles: DiagramStyles = {
  arrow_fill_color: '',
  arrow_stroke_width: 2,
  arrow_width: 10,
  arrowhead_angle: 60,
  barrier_stroke_dash_width: 4,
  barrier_stroke_width: 2,
  canvas_padding: 25,
  completion_height: 50,
  completion_stroke_width: 2,
  error_size: 30,
  error_stroke_width: 2,
  event_radius: 20,
  event_stroke_width: 2,
  event_value_font_family: 'Arial, Helvetica, sans-serif',
  event_value_font_size: 18,
  event_value_font_style: 'normal',
  event_value_font_weight: 'normal',
  frame_width: 30,
  ghost_opacity: 50,
  higher_order_angle: 18,
  higher_order_event_value_angle: 0,
  minimum_height: 0,
  minimum_width: 0,
  operator_corner_radius: 0,
  operator_stroke_width: 2,
  operator_title_font_family: 'Arial, Helvetica, sans-serif',
  operator_title_font_size: 24,
  operator_title_font_style: 'normal',
  operator_title_font_weight: 'normal',
  operator_height: 50,
  operator_spacing: 10,
  operator_stream_scale: 75,
  range_height: 15,
  range_stroke_width: 0,
  stacking_height: 50,
  stream_spacing: 20,
  stream_title_font_family: 'Arial, Helvetica, sans-serif',
  stream_title_font_size: 18,
  stream_title_font_style: 'normal',
  stream_title_font_weight: 'normal',
  stream_title_width: 100
}
